main: me.ma.skyblock.Main
name: Skyblock
description: "you already know"
version: 1.0.0
api-version: 1.21
commands:
  stat:
    description: Get/set/reset player stats
    usage: /stat <get|set|reset> ...
    permission: skyblock.admin
  resource:
    description: Get/set/reset player resources
    usage: /resource <get|set|reset> ...
    permission: skyblock.admin
  ability:
    description: Give/remove an ability to an item
    usage: /ability <add|remove> ...
    permission: skyblock.admin
  itemstat:
    description: Give/remove a stat on an item
    usage: /itemstat <add|remove> ...
    permission: skyblock.admin
permissions:
  skyblock.admin:
    default: op